### ISSUE TITLE
README.md should be extended

### ISSUE THREAD

**Issue by jirihnidek** [RedHatInsights/libygg#1]
I think that the `README.md` should contain following information:

1) Some build instructions
2) Requirements for building this library
3) It would be good to add example for another programming language or add instructions how to proceed with other programming language. Maybe it would be good to add more complex instruction to another `.md` file
4) There is no information about license or there is no `LICENSE` file.
5) No link for contacting developers (no email, no chat room)

**Comment by subpop** [comment]
I added more information to the README in https://github.com/RedHatInsights/libygg/commit/8312c9afcb868104368d6d4e14127cf1a5253159. The license is already present in the repository: https://github.com/RedHatInsights/libygg/blob/main/COPYING
