### ISSUE TITLE
File libygg.spec is missing

### ISSUE THREAD

**Issue by jirihnidek** [RedHatInsights/libygg#2]
I assume that there is intention to create some RPM package. Thus I believe that there should be `libygg.spec` for upstream.

**Comment by subpop** [comment]
Eventually, this will ship upstream in Fedora. The spec file that packages _libygg_ in Fedora will live in Fedora's infrastructure. If other distros end up picking up _yggdrasil_ and _libygg_, the build instructions for those distributions should reside in the distribution's infrastructure as well. We could add a `dist` directory (similarly to what we did in yggdrasil) here to aid developers in building SRPMs of this project.
